apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      labels:
        commit-sha: __COMMIT_SHA__
        gcb-build-id: __BUILD_ID__
        gcb-trigger-id: __TRIGGER_ID__
      annotations:
        run.googleapis.com/cloudsql-instances: __CLOUD_SQL_HOST__
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      timeoutSeconds: 600
      containers:
        - image: __IMAGE__
          resources:
            limits:
              cpu: 1000m
              memory: 2G
          env:
            - name: LANG
              value: ja_JP.UTF-8
            - name: TZ
              value: Asia/Tokyo
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_ENV
              value: production
            - name: RACK_ENV
              value: production
            - name: APP_HOST_NAME
              value: __APP_HOST_NAME__
            - name: CLOUD_RUN_HOST_NAME
              value: __CLOUD_RUN_HOST_NAME__
            - name: DB_NAME
              value: __DB_NAME__
            - name: DB_USER
              value: __DB_USER__
            - name: DB_HOST
              value: /cloudsql/__CLOUD_SQL_HOST__
            - name: GCS_BUCKET
              value: __GCS_BUCKET__
            - name: BASIC_AUTH_USER
              value: __BASIC_AUTH_USER__
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-rails-master-key
                  key: latest
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-db-pass
                  key: latest
            - name: GOOGLE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-google-credentials
                  key: latest
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-token
                  key: latest
            - name: DISCORD_NOTICE_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-notice-webhook-url
                  key: latest
            - name: DISCORD_INTRODUCTION_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-introduction-webhook-url
                  key: latest
            - name: DISCORD_ALL_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-all-webhook-url
                  key: latest
            - name: DISCORD_ADMIN_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-admin-webhook-url
                  key: latest
            - name: DISCORD_MENTOR_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-mentor-webhook-url
                  key: latest
            - name: DISCORD_BUG_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-bug-webhook-url
                  key: latest
            - name: DISCORD_REPORT_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-report-webhook-url
                  key: latest
            - name: DISCORD_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-guild-id
                  key: latest
            - name: DISCORD_TIMES_CHANNEL_CATEGORY_ID
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-times-channel-category-id
                  key: latest
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-bot-token
                  key: latest
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-client-id
                  key: latest
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-client-secret
                  key: latest
            - name: DISCORD_AUTHENTICATION_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-discord-authentication-url
                  key: latest
            - name: MISSION_CONTROL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-mission-control-username
                  key: latest
            - name: MISSION_CONTROL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-mission-control-password
                  key: latest
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-stripe-endpoint-secret
                  key: latest
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-basic-auth-password
                  key: latest
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-recaptcha-site-key
                  key: latest
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-recaptcha-secret-key
                  key: latest
            - name: ROLLBAR_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-rollbar-client-token
                  key: latest
            - name: ROLLBAR_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-rollbar-access-token
                  key: latest
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-slack-webhook-url
                  key: latest
            - name: GITHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-github-key
                  key: latest
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-github-secret
                  key: latest
            - name: OPEN_AI_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-open-ai-access-token
                  key: latest
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-anthropic-api-key
                  key: latest
            - name: PJORD_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-pjord-github-token
                  key: latest
            - name: STRIPE_TAX_RATE_ID
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-stripe-tax-rate-id
                  key: latest
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-stripe-public-key
                  key: latest
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-stripe-secret-key
                  key: latest
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-postmark-api-token
                  key: latest
            - name: PUBSUB_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-pubsub-audience
                  key: latest
            - name: PUBSUB_SERVICE_ACCOUNT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-pubsub-service-account-email
                  key: latest
            - name: PUBSUB_TOPIC
              valueFrom:
                secretKeyRef:
                  name: bootcamp-staging-pubsub-topic
                  key: latest
  traffic:
    - latestRevision: true
      percent: 100
