# tolerant of https://github.com/airbnb/ruby styles
LineLength:
  Max: 128

MethodLength:
  Max: 30

NumericLiterals:
  MinDigits: 12

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

DotPosition:
  Enabled: false

EmptyLinesAroundAccessModifier:
  Enabled: false

HandleExceptions:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IndentHash:
  Enabled: false

NegatedIf:
  Enabled: false

PercentLiteralDelimiters:
  Enabled: false

RedundantSelf:
  Enabled: false

Semicolon:
  Enabled: false

TrailingComma:
  Enabled: false

UselessAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Style/Lambda:
  Enabled: false

Style/GuardClause:
  Enabled: false

CoffeeScript:
  Enabled: true
  config_file: config/.coffeelint.json
