require:
  - rubocop-minitest
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  rubocop-fjord:
    - config/rubocop.yml
    - config/rails.yml

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/data/*
    - db/data_schema.rb
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
