ignore_unused_routes:
  - rails\/.*
  - static_pages#thanks
  - static_pages#retire
  - any_login\/.*
ignore_unreachable_actions:
  - rails\/.*
  - .*#admin_login\?
  - .*#admin_or_mentor_login\?
  - .*#adviser_login\?
  - .*#mentor_login\?
  - .*#staff_login\?
  - .*#paid_login\?
  - .*#staff_or_paid_login\?
  - .*#student_login\?
  - .*#policy
  - .*#require_staff_login
  - .*#require_admin_login
  - .*#require_mentor_login
  - .*#require_admin_or_mentor_login
  - mails#welcome
  - reports#convert_to_hour_minute
  - reports#convert_to_ceiled_hour
  - reports#practice_options
  - home#pricing
  - any_login\/.*
