steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args: ['build',
           '--no-cache',
           '-t', 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
           '-t', 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
           '.',
           '-f', 'Dockerfile']
  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ['push', 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  - id: SqlProxy
    name: "gcr.io/cloudsql-docker/gce-proxy:1.16"
    waitFor: ["-"]
    volumes:
      - name: db
        path: "/cloudsql"
    args: ["/cloud_sql_proxy", "-dir=/cloudsql", "-instances=$_CLOUD_SQL_HOST"]
  - id: DB_Migrate
    name: "asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    waitFor: ["Build"]
    volumes:
      - name: db
        path: "/cloudsql"
    args: ['bin/rails', 'db:create', 'db:migrate']
    env:
      - 'RAILS_ENV=production'
      - 'DB_HOST=/cloudsql/$_CLOUD_SQL_HOST'
      - 'DB_NAME=$_DB_NAME'
      - 'DB_PASS=$_DB_PASS'
      - 'DB_USER=$_DB_USER'
      - 'RAILS_MASTER_KEY=$_RAILS_MASTER_KEY'
  - id: Kill_SqlProxy
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["DB_Migrate"]
    entrypoint: "sh"
    args: ["-c", 'docker kill -s TERM $(docker ps -q --filter "volume=db")']
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--region=asia-northeast1'
      - '--quiet'
      - '--image=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--vpc-connector=bootcamp'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$_CLOUD_SQL_HOST'
      - '--memory'
      - '$_MEMORY'
      - '--set-env-vars=LANG=ja_JP.UTF-8'
      - '--set-env-vars=TZ=Asia/Tokyo'
      - '--set-env-vars=RAILS_LOG_TO_STDOUT=true'
      - '--set-env-vars=RAILS_ENV=production'
      - '--set-env-vars=RACK_ENV=production'
      - '--set-env-vars=APP_HOST_NAME=$_APP_HOST_NAME'
      - '--set-env-vars=RAILS_MASTER_KEY=$_RAILS_MASTER_KEY'
      - '--set-env-vars=DB_NAME=$_DB_NAME'
      - '--set-env-vars=DB_USER=$_DB_USER'
      - '--set-env-vars=DB_PASS=$_DB_PASS'
      - '--set-env-vars=DB_HOST=/cloudsql/$_CLOUD_SQL_HOST'
      - '--set-env-vars=GOOGLE_CREDENTIALS=$_GOOGLE_CREDENTIALS'
      - '--set-env-vars=GCS_BUCKET=$_GCS_BUCKET'
      - '--set-env-vars=REDIS_URL=$_REDIS_URL'
      - '--set-env-vars=TOKEN=$_TOKEN'
      - '--set-env-vars=$_ENVS'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
images:
  - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _MEMORY: 512M
  _SERVICE_NAME: _
  _LABELS: _
  _ENVS: _
  _TRIGGER_ID: _
  _CLOUD_SQL_HOST: _
  _RAILS_MASTER_KEY: _
  _APP_HOST_NAME: _
  _DB_NAME: _
  _DB_USER: _
  _DB_PASS: _
  _GOOGLE_CREDENTIALS: _
  _REDIS_URL: _
  _GCS_BUCKET: _
  _TOKEN: _
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bootcamp
timeout: 1200s
