steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '--cache-from'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'
  - id: SqlProxy
    name: "gcr.io/cloudsql-docker/gce-proxy:1.16"
    waitFor: ["-"]
    volumes:
      - name: db
        path: "/cloudsql"
    args: ["/cloud_sql_proxy", "-dir=/cloudsql", "-instances=$_CLOUD_SQL_HOST"]
  - id: DeleteDB
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - sql
      - databases
      - delete
      - hoge
      - '--instance bootcamp'
      - '--quiet'
- id: Kill_SqlProxy
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Task"]
    entrypoint: "sh"
    args: ["-c", 'docker kill -s TERM $(docker ps -q --filter "volume=db")']

images:
  - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _CLOUD_SQL_HOST: _
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bootcamp
timeout: 7200s
