eager_load.sql

SELECT
  "users"."id" AS t0_r0,
  "users"."login_name" AS t0_r1,
  "users"."email" AS t0_r2,
  "users"."crypted_password" AS t0_r3,
  "users"."salt" AS t0_r4,
  "users"."created_at" AS t0_r5,
  "users"."updated_at" AS t0_r6,
  "users"."remember_me_token" AS t0_r7,
  "users"."remember_me_token_expires_at" AS t0_r8,
  "users"."twitter_account" AS t0_r9,
  "users"."facebook_url" AS t0_r10,
  "users"."blog_url" AS t0_r11,
  "users"."company_id" AS t0_r12,
  "users"."description" AS t0_r13,
  "users"."accessed_at" AS t0_r14,
  "users"."github_account" AS t0_r15,
  "users"."adviser" AS t0_r16,
  "users"."nda" AS t0_r17,
  "users"."reset_password_token" AS t0_r18,
  "users"."reset_password_token_expires_at" AS t0_r19,
  "users"."reset_password_email_sent_at" AS t0_r20,
  "users"."mentor" AS t0_r21,
  "users"."graduated_on" AS t0_r22,
  "users"."course_id" AS t0_r23,
  "users"."retired_on" AS t0_r24,
  "users"."admin" AS t0_r25,
  "users"."job" AS t0_r26,
  "users"."organization" AS t0_r27,
  "users"."os" AS t0_r28,
  "users"."experience" AS t0_r29,
  "users"."retire_reason" AS t0_r30,
  "users"."trainee" AS t0_r31,
  "users"."free" AS t0_r32,
  "users"."customer_id" AS t0_r33,
  "users"."job_seeking" AS t0_r34,
  "users"."subscription_id" AS t0_r35,
  "users"."mail_notification" AS t0_r36,
  "users"."prefecture_code" AS t0_r37,
  "users"."job_seeker" AS t0_r38,
  "users"."github_id" AS t0_r39,
  "users"."github_collaborator" AS t0_r40,
  "users"."name" AS t0_r41,
  "users"."name_kana" AS t0_r42,
  "users"."satisfaction" AS t0_r43,
  "users"."opinion" AS t0_r44,
  "users"."retire_reasons" AS t0_r45,
  "users"."unsubscribe_email_token" AS t0_r46,
  "users"."mentor_memo" AS t0_r47,
  "users"."discord_account" AS t0_r48,
  "users"."times_url" AS t0_r49,
  "reports"."id" AS t1_r0,
  "reports"."user_id" AS t1_r1,
  "reports"."title" AS t1_r2,
  "reports"."description" AS t1_r3,
  "reports"."created_at" AS t1_r4,
  "reports"."updated_at" AS t1_r5,
  "reports"."reported_on" AS t1_r6,
  "reports"."wip" AS t1_r7,
  "reports"."emotion" AS t1_r8,
  "reports"."published_at" AS t1_r9
FROM
  "users"
  LEFT OUTER JOIN "reports" ON "reports"."user_id" = "users"."id"
WHERE
  "users"."job_seeking" = $ 1 [["job_seeking", true]]
