default: &default
  enable: false
  video_height: 1080
  video_width: 1920
  video_bitrate: 12000000
  video_frame_rate: 120
  audio_codec: 'aac'
  audio_bitrate: 128000
  container: 'mp4'
  location: 'asia-northeast1'
  pubsub_topic: 'bootcamp-transcoder-job-topic'

production:
  <<: *default
  enable: true

development:
  <<: *default

test:
  <<: *default
