<template lang="pug">
.categories-item.practices
  .categories-item__header
    .categories-item__title.a-placeholder
  .categories-item__description
    .is-long-text.a-placeholder
      p
  .categories-item__body
    .category-practices
      .category-practices-item
        .category-practices-item__header
          .category-practices-item__title
            .category-practices-item__title-link.a-placeholder
          .practice-status.category-practices-item__status.a-placeholder
        .m-user-icons
          .m-user-icons__items
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder

      .category-practices-item
        .category-practices-item__header
          .category-practices-item__title
            .category-practices-item__title-link.a-placeholder
          .practice-status.category-practices-item__status.a-placeholder
        .m-user-icons
          .m-user-icons__items
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder

      .category-practices-item
        .category-practices-item__header
          .category-practices-item__title
            .category-practices-item__title-link.a-placeholder
          .practice-status.category-practices-item__status.a-placeholder
        .m-user-icons
          .m-user-icons__items
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder

      .category-practices-item
        .category-practices-item__header
          .category-practices-item__title
            .category-practices-item__title-link.a-placeholder
          .practice-status.category-practices-item__status.a-placeholder
        .m-user-icons
          .m-user-icons__items
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
            .m-user-icons__item
              .m-user-icons__item-link
                .m-user-icons__item-icon.a-user-icon.a-placeholder
</template>
