// Configure your import map in config/importmap.rb.
import '@hotwired/turbo-rails'
import 'shortcut'
import 'current-date-time-setter'
import 'check_confirmation'
import 'unconfirmed-links-open'
import 'notifications_remove_after_open'
import 'warning'
import 'date-input-toggler'
import 'modal-switcher'
import 'copy-url'
import 'no_learn'
import 'training-info-toggler'
import 'courses-practices'
import 'upload-image-to-article'
import 'micro-report-form-tabs'
import 'footprints'
import 'diploma-upload'
