<template lang="pug">
.col-xxl-3.col-xl-4.col-lg-4.col-md-6.col-xs-12
  .users-item
    .users-item__inner.a-card
      .users-item__header
        .users-item__header-inner
          .users-item__header-start
            .users-item__icon
              .users-item__user-icon-image.a-user-icon.a-placeholder
          .users-item__header-end
            .card-list-item__rows
              .card-list-item__row
                .card-list-item-title.a-placeholder
              .card-list-item__row
                .card-list-item-meta
                  .card-list-item-meta__items
                    .card-list-item-meta__item.a-placeholder
                    .card-list-item-meta__item.a-placeholder
        .sns-links
          .sns-links__items.is-button-group.a-placeholder
      .users-item__body
        .users-item__description.a-short-text.a-placeholder
        .users-item__tags
          .tag-links
            .tag-links__items
              .tag-links__item.a-placeholder
              .tag-links__item.a-placeholder
      .completed-practices-progress
        .completed-practices-progress__bar-container
          .completed-practices-progress__bar.a-placeholder
        .completed-practices-progress__number.a-placeholder
      .card-footer
        .card-main-actions
          .card-main-actions__items
            .card-main-actions__item
              .following
                .following__summary
                  .a-button.is-secondary.is-sm.is-block.a-placeholder
</template>
