<template lang="pug">
.page-body
  .container.is-lg
    .thread
      .thread__user-link
        .thread__user-icon.a-user-icon.a-placeholder
      .thread__inner.a-card.is-loading
        .thread-header
          .thread-header__row
            .thread-header-metas.a-placeholder
          .thread-header__row
            .thread-header-title.a-placeholder
          .thread-header__row
            .thread-header-actions
              .thread-header-actions__start
                .thread-header-actions__action
                  .a-button.is-sm.is-block.a-placeholder
                .thread-header-actions__action
                  .a-button.is-sm.is-block.a-placeholder
              .thread-header-actions__end
                .thread-header-actions__action
                  .a-button.is-sm.is-secondary.is-block.a-placeholder
        .thread-category
        .thread__tags
        .thread__body
          .thread-question__body
            .thread__description.is-long-text.a-placeholder
              p
              p
              p
              p
              p
              p
              p
              p
              p
              p
              p
              p
            footer.card-footer
              .card-main-actions
                ul.card-main-actions__items
                  li.card-main-actions__item
                    .a-button.is-md.is-block.a-placeholder
</template>
