<template lang="pug">
.page-content
  .page-content-header
    .page-content-header__start
      .page-content-header__user
        .page-content-header__user-icon.a-user-icon.a-placeholder
    .page-content-header__end
      .page-content-header__row
        .page-content-header__before-title.a-placeholder
        .thread-header-title.a-placeholder
      .page-content-header__row
        .page-content-header__title.a-placeholder
      .page-content-header__row
        .page-content-header-actions
          .page-content-header-actions__start
            .page-content-header-actions__action
              .a-button.is-sm.is-block.a-placeholder
            .page-content-header-actions__action
              .a-button.is-sm.is-block.a-placeholder
          .page-content-header-actions__end
            .page-content-header-actions__action
              .a-button.is-sm.is-secondary.is-block.a-placeholder
  .a-card.is-loading
    .card-body
      .card__description
        .a-long-text.is-md.a-placeholder
          p
          p
          p
          p
          p
          p
          p
          p
          p
          p
          p
          p
        footer.card-footer
          .card-main-actions
            ul.card-main-actions__items
              li.card-main-actions__item
                .a-button.is-sm.is-block.a-placeholder
</template>
