steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - 'docker pull asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0'
    id: Fetch
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - '--cache-from'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/cloudsql-docker/gce-proxy:1.16'
    args:
      - /cloud_sql_proxy
      - '-dir=/cloudsql'
      - '-instances=$_CLOUD_SQL_HOST'
    id: SqlProxy
    waitFor:
      - '-'
    volumes:
      - name: db
        path: /cloudsql
  - name: 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    env:
      - RAILS_ENV=production
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - DB_HOST=/cloudsql/$_CLOUD_SQL_HOST
      - DB_NAME=$_DB_NAME
      - DB_PASS=$_DB_PASS
      - DB_USER=$_DB_USER
      - RAILS_MASTER_KEY=$_RAILS_MASTER_KEY
    args:
      - bin/rails
      - 'db:reset'
    id: DB_Migrate
    waitFor:
      - Push
    volumes:
      - name: db
        path: /cloudsql
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker kill -s TERM $(docker ps -q --filter "volume=db")
    id: Kill_SqlProxy
    waitFor:
      - DB_Migrate
    entrypoint: sh
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--region=asia-northeast1'
      - '--quiet'
      - '--image=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--clear-vpc-connector'
      - '--add-cloudsql-instances'
      - $_CLOUD_SQL_HOST
      - '--memory'
      - $_MEMORY
      - '--set-env-vars=LANG=ja_JP.UTF-8'
      - '--set-env-vars=TZ=Asia/Tokyo'
      - '--set-env-vars=RAILS_SERVE_STATIC_FILES=true'
      - '--set-env-vars=RAILS_LOG_TO_STDOUT=true'
      - '--set-env-vars=RAILS_ENV=production'
      - '--set-env-vars=RACK_ENV=production'
      - '--set-env-vars=APP_HOST_NAME=$_APP_HOST_NAME'
      - '--set-env-vars=CLOUD_RUN_HOST_NAME=$_CLOUD_RUN_HOST_NAME'
      - '--set-env-vars=RAILS_MASTER_KEY=$_RAILS_MASTER_KEY'
      - '--set-env-vars=DB_NAME=$_DB_NAME'
      - '--set-env-vars=DB_USER=$_DB_USER'
      - '--set-env-vars=DB_PASS=$_DB_PASS'
      - '--set-env-vars=DB_HOST=/cloudsql/$_CLOUD_SQL_HOST'
      - '--set-env-vars=GOOGLE_CREDENTIALS=$_GOOGLE_CREDENTIALS'
      - '--set-env-vars=GCS_BUCKET=$_GCS_BUCKET'
      - '--set-env-vars=REDIS_URL=$_REDIS_URL'
      - '--set-env-vars=TOKEN=$_TOKEN'
      - '--set-env-vars=DISCORD_NOTICE_WEBHOOK_URL=$_DISCORD_NOTICE_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_ALL_WEBHOOK_URL=$_DISCORD_ALL_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_ADMIN_WEBHOOK_URL=$_DISCORD_ADMIN_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_BUG_WEBHOOK_URL=$_DISCORD_BUG_WEBHOOK_URL'
      - '--set-env-vars=BASIC_AUTH_USER=$_BASIC_AUTH_USER'
      - '--set-env-vars=BASIC_AUTH_PASSWORD=$_BASIC_AUTH_PASSWORD'
      - '--set-env-vars=ROLLBAR_CLIENT_TOKEN=$_ROLLBAR_CLIENT_TOKEN'
      - '--set-env-vars=APPSIGNAL_PUSH_API_KEY=$_APPSIGNAL_PUSH_API_KEY'
      - '--set-env-vars=$_ENVS'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
    id: Deploy
    entrypoint: gcloud
  - name: 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    env:
      - DB_NAME=$_DB_NAME
      - DEPLOY_NOTIFY_WEBHOOK_URL=$_DEPLOY_NOTIFY_WEBHOOK_URL
    args:
      - bin/notify
    id: Notify
    waitFor:
      - Deploy
timeout: 7200s
images:
  - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _BASIC_AUTH_USER: _
  _BASIC_AUTH_PASSWORD: _
  _DISCORD_ALL_WEBHOOK_URL: _
  _REDIS_URL: _
  _TRIGGER_ID: _
  _DB_NAME: _
  _APPSIGNAL_PUSH_API_KEY: _
  _GCS_BUCKET: _
  _MEMORY: 2GB
  _DB_PASS: _
  _CLOUD_SQL_HOST: _
  _GOOGLE_CREDENTIALS: _
  _APP_HOST_NAME: _
  _RAILS_MASTER_KEY: _
  _DB_USER: _
  _ROLLBAR_CLIENT_TOKEN: _
  _ENVS: _
  _SERVICE_NAME: _
  _DISCORD_NOTICE_WEBHOOK_URL: _
  _CLOUD_RUN_HOST_NAME: _
  _LABELS: _
  _TOKEN: _
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bootcamp
