steps:
  - id: Fetch
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - 'docker pull asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0'
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - .
      - '-f'
      - Dockerfile
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    waitFor:
      - Build
  # Cloud Runサービスを停止してDB接続を切断
  # Cloud SQLでは管理者権限がないためpg_terminate_backendが使えない
  # 代わりにCloud Runサービスを停止することで接続を確実に切断する
  - id: StopCloudRun
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "Stopping Cloud Run service to disconnect database connections..."

        # サービスが存在するか確認
        if gcloud run services describe $_SERVICE_NAME --region=asia-northeast1 --quiet 2>/dev/null; then
          # サービスのインスタンス数を0に設定して接続を切断
          gcloud run services update $_SERVICE_NAME \
            --region=asia-northeast1 \
            --max-instances=0 \
            --quiet

          echo "Cloud Run service stopped. Waiting 30 seconds for connections to drain..."
          sleep 30
        else
          echo "Cloud Run service does not exist yet. Skipping stop."
        fi
    waitFor:
      - Push
  - id: SqlProxy
    name: 'gcr.io/cloudsql-docker/gce-proxy:1.16'
    args:
      - /cloud_sql_proxy
      - '-dir=/cloudsql'
      - '-instances=$_CLOUD_SQL_HOST'
    waitFor:
      - StopCloudRun
    volumes:
      - name: db
        path: /cloudsql
  # Cloud SQL Proxyの起動を待つ
  - id: WaitForProxy
    name: 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    args:
      - bash
      - '-c'
      - |
        set -euo pipefail

        echo "Waiting for Cloud SQL Proxy to be ready..."
        TIMEOUT=60
        ELAPSED=0

        while [ $$ELAPSED -lt $$TIMEOUT ]; do
          echo "Attempting database connection... ($$ELAPSED/$$TIMEOUT seconds)"
          OUTPUT=$$(cat <<'TESTEOF' | bin/rails runner - 2>&1
        begin
          ActiveRecord::Base.connection.execute("SELECT 1")
          puts "Database connection successful"
          exit 0
        rescue => e
          puts "Connection failed: #{e.message}"
          exit 1
        end
        TESTEOF
          )
          EXITCODE=$$?
          if [ $$EXITCODE -eq 0 ]; then
            echo "$$OUTPUT"
            echo "Cloud SQL Proxy is ready."
            exit 0
          else
            echo "Rails runner output: $$OUTPUT"
            echo "Database not ready yet, waiting..."
          fi
          sleep 2
          ELAPSED=$$(($$ELAPSED + 2))
        done

        echo "ERROR: Timeout waiting for Cloud SQL Proxy after $$TIMEOUT seconds"
        exit 1
    waitFor:
      - StopCloudRun
    volumes:
      - name: db
        path: /cloudsql
    env:
      - RAILS_ENV=production
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - DB_HOST=/cloudsql/$_CLOUD_SQL_HOST
      - DB_NAME=postgres
      - DB_PASS=$_DB_PASS
      - DB_USER=$_DB_USER
      - RAILS_MASTER_KEY=$_RAILS_MASTER_KEY
      - APP_HOST_NAME=$_APP_HOST_NAME
  # データベースを削除
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - sql
      - databases
      - delete
      - bootcamp_staging
      - '--instance=bootcamp'
      - '--quiet'
    id: DeleteDB
    waitFor:
      - WaitForProxy
    entrypoint: gcloud
    volumes:
      - name: db
        path: /cloudsql
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - sql
      - databases
      - create
      - bootcamp_staging
      - '--instance=bootcamp'
      - '--quiet'
    id: CreateDB
    waitFor:
      - DeleteDB
    entrypoint: gcloud
    volumes:
      - name: db
        path: /cloudsql
  - id: DBMigrate
    name: 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    args:
      - bin/rails
      - db:migrate
      - db:seed
    waitFor:
      - DeleteDB
    volumes:
      - name: db
        path: /cloudsql
    env:
      - RAILS_ENV=production
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - DB_HOST=/cloudsql/$_CLOUD_SQL_HOST
      - DB_NAME=$_DB_NAME
      - DB_PASS=$_DB_PASS
      - DB_USER=$_DB_USER
      - RAILS_MASTER_KEY=$_RAILS_MASTER_KEY
      - APP_HOST_NAME=$_APP_HOST_NAME
  - id: Kill_SqlProxy
    name: gcr.io/cloud-builders/docker
    entrypoint: sh
    args:
      - '-c'
      - docker kill -s TERM $(docker ps -q --filter "volume=db")
    waitFor:
      - DBMigrate
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--region=asia-northeast1'
      - '--quiet'
      - '--image=asia.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--clear-vpc-connector'
      - '--add-cloudsql-instances'
      - $_CLOUD_SQL_HOST
      - '--memory'
      - $_MEMORY
      - '--timeout'
      - '10m'
      - '--set-env-vars=LANG=ja_JP.UTF-8'
      - '--set-env-vars=TZ=Asia/Tokyo'
      - '--set-env-vars=RAILS_SERVE_STATIC_FILES=true'
      - '--set-env-vars=RAILS_LOG_TO_STDOUT=true'
      - '--set-env-vars=RAILS_ENV=production'
      - '--set-env-vars=RACK_ENV=production'
      - '--set-env-vars=APP_HOST_NAME=$_APP_HOST_NAME'
      - '--set-env-vars=CLOUD_RUN_HOST_NAME=$_CLOUD_RUN_HOST_NAME'
      - '--set-env-vars=RAILS_MASTER_KEY=$_RAILS_MASTER_KEY'
      - '--set-env-vars=DB_NAME=$_DB_NAME'
      - '--set-env-vars=DB_USER=$_DB_USER'
      - '--set-env-vars=DB_PASS=$_DB_PASS'
      - '--set-env-vars=DB_HOST=/cloudsql/$_CLOUD_SQL_HOST'
      - '--set-env-vars=GOOGLE_CREDENTIALS=$_GOOGLE_CREDENTIALS'
      - '--set-env-vars=GCS_BUCKET=$_GCS_BUCKET'
      - '--set-env-vars=TOKEN=$_TOKEN'
      - '--set-env-vars=DISCORD_NOTICE_WEBHOOK_URL=$_DISCORD_NOTICE_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_INTRODUCTION_WEBHOOK_URL=$_DISCORD_INTRODUCTION_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_ALL_WEBHOOK_URL=$_DISCORD_ALL_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_ADMIN_WEBHOOK_URL=$_DISCORD_ADMIN_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_MENTOR_WEBHOOK_URL=$_DISCORD_MENTOR_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_BUG_WEBHOOK_URL=$_DISCORD_BUG_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_REPORT_WEBHOOK_URL=$_DISCORD_REPORT_WEBHOOK_URL'
      - '--set-env-vars=DISCORD_GUILD_ID=$_DISCORD_GUILD_ID'
      - '--set-env-vars=DISCORD_TIMES_CHANNEL_CATEGORY_ID=$_DISCORD_TIMES_CHANNEL_CATEGORY_ID'
      - '--set-env-vars=DISCORD_BOT_TOKEN=$_DISCORD_BOT_TOKEN'
      - '--set-env-vars=GOOD_JOB_USERNAME=$_GOOD_JOB_USERNAME'
      - '--set-env-vars=GOOD_JOB_PASSWORD=$_GOOD_JOB_PASSWORD'
      - '--set-env-vars=STRIPE_ENDPOINT_SECRET=$_STRIPE_ENDPOINT_SECRET'
      - '--set-env-vars=BASIC_AUTH_USER=$_BASIC_AUTH_USER'
      - '--set-env-vars=BASIC_AUTH_PASSWORD=$_BASIC_AUTH_PASSWORD'
      - '--set-env-vars=RECAPTCHA_SITE_KEY=$_RECAPTCHA_SITE_KEY'
      - '--set-env-vars=RECAPTCHA_SECRET_KEY=$_RECAPTCHA_SECRET_KEY'
      - '--set-env-vars=ROLLBAR_CLIENT_TOKEN=$_ROLLBAR_CLIENT_TOKEN'
      - '--set-env-vars=OPEN_AI_ACCESS_TOKEN=$_OPEN_AI_ACCESS_TOKEN'
      - '--set-env-vars=STRIPE_TAX_RATE_ID=$_STRIPE_TAX_RATE_ID'
      - '--set-env-vars=DISCORD_CLIENT_ID=$_DISCORD_CLIENT_ID'
      - '--set-env-vars=DISCORD_CLIENT_SECRET=$_DISCORD_CLIENT_SECRET'
      - '--set-env-vars=DISCORD_AUTHENTICATION_URL=$_DISCORD_AUTHENTICATION_URL'
      - '--set-env-vars=PUBSUB_AUDIENCE=$_PUBSUB_AUDIENCE'
      - '--set-env-vars=PUBSUB_SERVICE_ACCOUNT_EMAIL=$_PUBSUB_SERVICE_ACCOUNT_EMAIL'
      - '--set-env-vars=$_ENVS'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
  - id: Notify
    name: 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    args:
      - bin/notify
    waitFor:
      - Deploy
    env:
      - DB_NAME=$_DB_NAME
      - DEPLOY_NOTIFY_WEBHOOK_URL=$_DEPLOY_NOTIFY_WEBHOOK_URL
timeout: 7200s
images:
  - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:latest'
