name: Create a release pull-request
on:
  push:
    branches:
      - main
      - chore/custom-pr-release-action
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: create-release-pr
        uses: komagata/git-pr-release-action@master
        with:
          base: production
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          assign: true
