name: Create a release pull-request
on:
  push:
    branches:
      - main
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: production
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          assign: true
