on:
  pull_request:
    types: [review_requested, review_request_removed, edited, closed]

jobs:
  post_pr_event:
    runs-on: ubuntu-latest
    steps:
    - name: post review requested pr event
      run: |
        curl -X POST https://fjord-choice.herokuapp.com/api/pulls \
             -H 'Content-Type: application/json' \
             -H 'Authorization: Token ${{ secrets.FJORD_CHOICE_TOKEN }}' \
             -d '{"title": ${{ toJson(github.event.pull_request.title) }},
                  "number": ${{ github.event.pull_request.number }},
                  "state": ${{ toJson(github.event.pull_request.state) }},
                  "reviewer_uids": ${{ toJson(github.event.pull_request.requested_reviewers.*.id) }}
                  }'
